Removes bootstrap-switch include
ISISScientificComputing/autoreduce pull request #1227
Opened 2021-03-22 08:57 UTC by dtasev

### Summary of work
Removes unused JS and CSS imports of Bootstrap-Switch. Usage of this was removed in #1174 but it seems there's some leftover imports.

### How to test your work
Tests should pass.

### Additional comments
 

Fixes #1220

**Before merging ensure the release notes have been updated**

2021-03-22 10:46 UTC, rickybassom requested changes
Looks good. Only I think it's referenced here too? https://github.com/ISISScientificComputing/autoreduce/blob/1220_remove_bootstrap_switch/WebApp/autoreduce_webapp/static/javascript/run_variables.js#L62

2021-03-22 11:40 UTC, dtasev commented
Good catch! I'll change the func to just be in plain JS as it's simpler anyway 😆

2021-03-22 18:46 UTC, dtasev commented
Converting to draft to fix another issue with selenium tests locally

2021-03-23 10:08 UTC, dtasev commented
This is ready for review after the fixes in #1232

2021-03-23 10:14 UTC, rickybassom approved these changes

2021-03-23 10:26 UTC, merged