Selenium Base: In progress
ISISScientificComputing/autoreduce pull request #930
Opened 2020-11-17 18:46 UTC by keiranjprice101

### Summary of work

### How to test your work
 

### Additional comments
 

Fixes #xyz

**Before merging ensure the release notes have been updated**

2020-11-25 22:34 UTC, rickybassom commented
The `build-autoreduction` composite action, which you can in your workflow here, has been merged into master https://github.com/ISISScientificComputing/autoreduce/pull/932

2020-12-02 16:18 UTC, rickybassom requested changes
Looks really good overall. I like the OOP approach to the tests.

Can you also add header comments to the `__init__.py` files?

2020-12-02 16:18 UTC, rickybassom commented on webtests/pages/component_mixins/tour_mixin.py
> +        :return: (bool) True if tour is visible, false otherwise
```suggestion
        :return: (bool) True if tour is visible, False otherwise
```

2020-12-02 16:18 UTC, rickybassom commented on webtests/pages/component_mixins/tour_mixin.py
> +        :return: (bool) True if tour is visible, false otherwise
```suggestion
        :return: (bool) True if tour is visible, False otherwise
```

2020-12-02 16:18 UTC, rickybassom commented on webtests/pages/overview_page.py
> +        connecting to / and not /overview Once we have a better way to simulate logging in on the
```suggestion
        connecting to / and not /overview. Once we have a better way to simulate logging in on the
```

2020-12-02 16:18 UTC, rickybassom commented on webtests/pages/overview_page.py
> +        :return:
```suggestion
        :return: The OverviewPage object
```

2020-12-02 16:18 UTC, rickybassom commented on webtests/runner.py
> +                        help="target environment type: remote or local. Default is remote")
```suggestion
                        help="Target environment type: remote or local. Default is remote")
```

2020-12-02 16:18 UTC, rickybassom commented on webtests/runner.py
> +                        help="target url to run tests against. Default is localhost:8000."
```suggestion
                        help="Target url to run tests against. Default is localhost:8000."
```

2020-12-02 16:18 UTC, rickybassom commented on webtests/tests/base_tests.py
> +        When Help page link is clicked
```suggestion
        When: Help page link is clicked
```

2020-12-02 16:18 UTC, rickybassom commented on webtests/tests/test_overview_page.py
> +        Tests Tour run through on overview page
```suggestion
        Tests: Tour run through on overview page
```

Add `When:`

2020-12-02 16:21 UTC, rickybassom requested changes

2020-12-02 16:21 UTC, rickybassom commented on webtests/README.md
> +#webtests
```suggestion
# webtests
```

2020-12-02 21:13 UTC, keiranjprice101 commented
@rickybassom I'll grab you at some point tomorrow to discuss the actions.

2020-12-16 09:25 UTC, merged